name: Unity Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Test
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2021.1.18f1

  build:
    name: Build project
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.1.18f1
          targetPlatform: StandaloneWindows64